name: guillotina_nuclia

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11"]
        database: ["DUMMY", "postgres"]
    env:
      DATABASE: ${{ matrix.database }}
    steps:
      # Checkout the repository first
      - uses: actions/checkout@v2

      # Setup the python version
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      # Linters and typing
      - name: Pre-checks
        run: |
          # Install
          pip install flake8 isort black==22.10.0

          # Run commands
          flake8 guillotina_nuclia --config=setup.cfg
          isort -c -rc guillotina_nuclia
          black --check --verbose guillotina_nuclia
          
      # Run tests
      - name: Run tests
        env:
          NUA_KEY: ${{ secrets.NUA_KEY }}
          KBID: ${{ secrets.KBID }}
          APIKEY: ${{ secrets.APIKEY }}
        run: |
          # Install package with test dependecies
          pip install -e .[test]

          # Run tests
          pytest --capture=no --tb=native -v guillotina_nuclia --cov=guillotina_nuclia --cov-report term-missing --cov-append guillotina_nuclia
